services:
  postgres:
    image: postgres:16-alpine
    container_name: checkout_payment_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: checkout
      POSTGRES_PASSWORD: checkout_dev
      POSTGRES_DB: checkout_payment
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U checkout -d checkout_payment']
      interval: 5s
      timeout: 5s
      retries: 10

  postgres-test:
    image: postgres:16-alpine
    container_name: checkout_payment_db_test
    restart: unless-stopped
    environment:
      POSTGRES_USER: checkout
      POSTGRES_PASSWORD: checkout_dev
      POSTGRES_DB: checkout_payment_test
    ports:
      - '5435:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U checkout -d checkout_payment_test']
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
  postgres_test_data:
